version: "3.8"

services:
  web:
    build:
      context: .
      args:
        VERSION: 0.99.1
        ARCH: arm64
    ports:
      - "8081:80"
    environment:
      - DD_AGENT_HOST=datadog-simple-php
      - DD_TRACE_DEBUG=true
      - DD_TRACE_STARTUP_LOGS=true
      - DD_TRACE_AGENT_PORT=8126
      - DD_SERVICE=php_app
      - DD_ENV=php
  datadog:
    image: "gcr.io/datadoghq/agent:7.41.1"
    container_name: datadog-simple-php
    env_file:
      - ~/sandbox.docker.env
    ports:
      - 8126:8126/tcp
    environment:
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOG_LEVEL=INFO
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_TRACE_DEBUG=true
    # - DD_CONTAINER_EXCLUDE="name:datadog-simple-php"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
